services:
  - type: web
    name: questmatch-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        fromContext: secret
      - key: TURSO_URL
        fromContext: secret
      - key: TURSO_AUTH_TOKEN
        fromContext: secret
      - key: NODE_ENV
        value: production
